# Generated by Django 4.1.3 on 2022-11-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="tile_coord_q",
        ),
        migrations.RemoveField(
            model_name="action",
            name="tile_coord_r",
        ),
        migrations.RemoveField(
            model_name="drop",
            name="tile_coord_q",
        ),
        migrations.RemoveField(
            model_name="drop",
            name="tile_coord_r",
        ),
        migrations.RemoveField(
            model_name="occupiedtile",
            name="coord_q",
        ),
        migrations.RemoveField(
            model_name="occupiedtile",
            name="coord_r",
        ),
        migrations.RemoveField(
            model_name="playeringame",
            name="start_tile_coord_q",
        ),
        migrations.RemoveField(
            model_name="playeringame",
            name="start_tile_coord_r",
        ),
        migrations.RemoveField(
            model_name="randomevent",
            name="tile_coord_q",
        ),
        migrations.RemoveField(
            model_name="randomevent",
            name="tile_coord_r",
        ),
        migrations.AddField(
            model_name="action",
            name="tile_col",
            field=models.IntegerField(
                help_text="The grid column of the action in the offset `odd-q` coordinate system.", null=True
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="tile_row",
            field=models.IntegerField(
                help_text="The grid row of the action in the offset `odd-q` coordinate system.", null=True
            ),
        ),
        migrations.AddField(
            model_name="drop",
            name="tile_col",
            field=models.IntegerField(
                default=0, help_text="The grid column of the drop in the offset `odd-q` coordinate system."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drop",
            name="tile_row",
            field=models.IntegerField(
                default=0, help_text="The grid row of the drop in the offset `odd-q` coordinate system."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="occupiedtile",
            name="col",
            field=models.IntegerField(
                default=0, help_text="The grid column of the tile in the offset `odd-q` coordinate system."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="occupiedtile",
            name="row",
            field=models.IntegerField(
                default=0, help_text="The grid row of the tile in the offset `odd-q` coordinate system."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playeringame",
            name="start_tile_col",
            field=models.IntegerField(
                default=0, help_text="The grid column of the start tile in the offset `odd-q` coordinate system."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playeringame",
            name="start_tile_row",
            field=models.IntegerField(
                default=0, help_text="The grid row of the start tile in the offset `odd-q` coordinate system."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="randomevent",
            name="tile_col",
            field=models.IntegerField(
                help_text="The grid column of the event in the offset `odd-q` coordinate system.", null=True
            ),
        ),
        migrations.AddField(
            model_name="randomevent",
            name="tile_row",
            field=models.IntegerField(
                help_text="The grid row of the event in the offset `odd-q` coordinate system.", null=True
            ),
        ),
    ]
