# Generated by Django 4.1.3 on 2022-11-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_change_tiles_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="allowed",
            field=models.BooleanField(db_index=True, default=True, help_text="Whether the player is allowed or not."),
        ),
    ]
