# Generated by Django 4.1.3 on 2022-11-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_player_allowed_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="occupiedtile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="When the tile was last updated."),
        ),
        migrations.AlterField(
            model_name="game",
            name="current_turn_started_at",
            field=models.DateTimeField(auto_now_add=True, help_text="When the current turn started."),
        ),
    ]
