# Generated by Django 4.1.3 on 2022-11-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_occupied_tile_last_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="occupiedtile",
            name="nb_updates",
            field=models.IntegerField(default=1, help_text="Number of times the tile has been updated."),
        ),
    ]
