# Generated by Django 4.1.3 on 2022-11-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_occupied_tile_nb_updates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occupiedtile",
            name="nb_updates",
        ),
    ]
