# Generated by Django 4.1.3 on 2022-11-19 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_game_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="player_in_game",
            field=models.ForeignKey(
                help_text="Player in game that did the action.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.playeringame",
            ),
        ),
        migrations.AddField(
            model_name="occupiedtile",
            name="player_in_game",
            field=models.ForeignKey(
                help_text="Player in game that occupies the tile.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.playeringame",
            ),
        ),
    ]
