# Generated by Django 4.1.3 on 2022-11-19 04:04
from typing import Any

from django.apps.registry import Apps
from django.db import migrations
from django.db.models import F, OuterRef, Subquery


def update_occupied_tiles(apps: Apps, schema_editor: Any) -> None:
    OccupiedTile = apps.get_model("core", "OccupiedTile")
    PlayerInGame = apps.get_model("core", "PlayerInGame")
    OccupiedTile.objects.annotate(
        new_player_in_game=Subquery(
            PlayerInGame.objects.filter(game_id=OuterRef("game_id"), player_id=OuterRef("player_id")).values("id")[:1]
        )
    ).update(player_in_game=F("new_player_in_game"))


def udpate_actions(apps: Apps, schema_editor: Any) -> None:
    Action = apps.get_model("core", "Action")
    PlayerInGame = apps.get_model("core", "PlayerInGame")
    Action.objects.annotate(
        new_player_in_game=Subquery(
            PlayerInGame.objects.filter(game_id=OuterRef("game_id"), player_id=OuterRef("player_id")).values("id")[:1]
        )
    ).update(player_in_game=F("new_player_in_game"))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_link_occupied_tiles_and_actions_to_player_in_game"),
    ]

    operations = [
        migrations.RunPython(update_occupied_tiles, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(udpate_actions, reverse_code=migrations.RunPython.noop),
    ]
