# Generated by Django 4.1.3 on 2022-11-19 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_fill_occupied_tiles_and_actions_player_in_game_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="game",
        ),
        migrations.RemoveField(
            model_name="action",
            name="player",
        ),
        migrations.RemoveField(
            model_name="occupiedtile",
            name="game",
        ),
        migrations.RemoveField(
            model_name="occupiedtile",
            name="player",
        ),
        migrations.AlterField(
            model_name="action",
            name="player_in_game",
            field=models.ForeignKey(
                help_text="Player in game that did the action.",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.playeringame",
            ),
        ),
        migrations.AlterField(
            model_name="occupiedtile",
            name="player_in_game",
            field=models.ForeignKey(
                help_text="Player in game that occupies the tile.",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.playeringame",
            ),
        ),
    ]
