# Generated by Django 4.1.3 on 2022-11-19 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_back_game_to_occupied_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occupiedtile",
            name="game",
            field=models.ForeignKey(
                help_text="Game the tile is in.", on_delete=django.db.models.deletion.CASCADE, to="core.game"
            ),
        ),
        migrations.AlterField(
            model_name="occupiedtile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True, help_text="When the tile was last updated."),
        ),
        migrations.AlterUniqueTogether(
            name="occupiedtile",
            unique_together={("game", "col", "row")},
        ),
        migrations.AlterUniqueTogether(
            name="playeringame",
            unique_together={("player", "game")},
        ),
    ]
