# Generated by Django 4.1.3 on 2022-11-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_add_some_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drop",
            name="coins",
        ),
        migrations.RemoveField(
            model_name="randomevent",
            name="confirmed_at",
        ),
        migrations.RemoveField(
            model_name="randomevent",
            name="drop_coins_amount",
        ),
        migrations.AddField(
            model_name="drop",
            name="nb_actions",
            field=models.FloatField(default=0, help_text="Number of action points in the drop."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="randomevent",
            name="drop_actions_amount",
            field=models.FloatField(help_text="Amount of coins in the drop.", null=True),
        ),
    ]
