# Generated by Django 4.1.3 on 2022-11-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_game_use_actions_not_coins"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="playeringame",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="playeringame",
            name="dead_at",
            field=models.DateTimeField(help_text="When the player died. Null if the player is alive.", null=True),
        ),
        migrations.AddConstraint(
            model_name="playeringame",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dead_at__isnull", True)),
                fields=("game", "player"),
                name="core_playeringame_game_player_is_alive",
            ),
        ),
        migrations.RemoveField(
            model_name="playeringame",
            name="is_alive",
        ),
    ]
