# Generated by Django 4.1.3 on 2022-11-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_player_in_game_dead_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playeringame",
            name="coins",
        ),
        migrations.AddField(
            model_name="playeringame",
            name="banked_actions",
            field=models.PositiveIntegerField(
                default=0, help_text="Current number of banked actions points of the player."
            ),
        ),
        migrations.AlterField(
            model_name="playeringame",
            name="ended_turn",
            field=models.PositiveIntegerField(blank=True, help_text="Turn number when the player died.", null=True),
        ),
        migrations.AlterField(
            model_name="randomevent",
            name="drop_actions_amount",
            field=models.FloatField(help_text="Amount of actions points in the drop.", null=True),
        ),
    ]
