# Generated by Django 4.1.3 on 2022-11-21 04:49
from typing import Any

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.models import F, OuterRef, Subquery


def set_started_at(apps: Apps, schema_editor: Any) -> None:
    PlayerInGame = apps.get_model("core", "PlayerInGame")
    Action = apps.get_model("core", "Action")
    PlayerInGame.objects.annotate(
        first_action_date=Subquery(
            Action.objects.filter(player_in_game_id=OuterRef("id"))
            .order_by("confirmed_at")
            .values("confirmed_at")[:1]
        )
    ).update(started_at=F("first_action_date"))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_game_use_actions_not_coins_bis"),
    ]

    operations = [
        migrations.AddField(
            model_name="playeringame",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, help_text="When the player joined the game.", null=True),
        ),
        migrations.RunPython(set_started_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="playeringame",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, help_text="When the player joined the game."),
        ),
    ]
