# Generated by Django 4.1.3 on 2022-11-21 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_player_in_game_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="playeringame",
            name="killed_by",
            field=models.ForeignKey(
                help_text="Who killed the player.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kills",
                related_query_name="kills",
                to="core.playeringame",
            ),
        ),
    ]
