# Generated by Django 4.1.3 on 2022-11-23 21:04
from typing import Any

from django.apps.registry import Apps
from django.db import migrations, models


def set_actions_state(apps: Apps, schema_editor: Any) -> None:
    """Set the state of all confirmed actions in free* games to SUCCESSFUL."""
    Action = apps.get_model("core", "Action")
    Action.objects.filter(confirmed_at__isnull=False).update(state="successful")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_player_in_game_killed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("confirmed", "Confirmed"),
                    ("successful", "Successful"),
                    ("failed", "Failed"),
                ],
                default="created",
                help_text="State of the action.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="confirmed_at",
            field=models.DateTimeField(db_index=True, help_text="When the action was confirmed.", null=True),
        ),
        migrations.RunPython(
            set_actions_state,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="action",
            constraint=models.CheckConstraint(
                check=models.Q(("state", "created"), ("confirmed_at__isnull", False), _connector="OR"),
                name="core_action_confirmed_at_not_null_if_not_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="action",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("state", "created"), _negated=True), ("confirmed_at__isnull", True), _connector="OR"
                ),
                name="core_action_confirmed_at_null_if_created",
            ),
        ),
    ]
