# Generated by Django 4.1.3 on 2022-11-23 21:54
from typing import Any

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.models import F, OuterRef, Subquery


def set_game_field(apps: Apps, schema_editor: Any) -> None:
    Action = apps.get_model("core", "Action")
    PlayerInGame = apps.get_model("core", "PlayerInGame")

    Action.objects.annotate(
        new_game_id=Subquery(PlayerInGame.objects.filter(id=OuterRef("player_in_game_id")).values("game_id")[:1])
    ).update(game=F("new_game_id"))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_action_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="game",
            field=models.ForeignKey(
                help_text="Game the action was done in.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.game",
            ),
        ),
        migrations.RunPython(set_game_field, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="action",
            name="game",
            field=models.ForeignKey(
                help_text="Game the action was done in.", on_delete=django.db.models.deletion.CASCADE, to="core.game"
            ),
        ),
    ]
