# Generated by Django 4.1.3 on 2022-11-23 23:37
from typing import Any

from django.apps.registry import Apps
from django.db import migrations, models


def update_states(apps: Apps, schema_editor: Any) -> None:
    Action = apps.get_model("core", "Action")
    Action.objects.filter(state="successful").update(state="success")
    Action.objects.filter(state="failed").update(state="failure")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_add_back_game_to_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("confirmed", "Confirmed"),
                    ("success", "Success"),
                    ("failure", "Failure"),
                ],
                default="created",
                help_text="State of the action.",
                max_length=255,
            ),
        ),
        migrations.RunPython(update_states, migrations.RunPython.noop),
    ]
