# Generated by Django 4.1.3 on 2022-11-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_rename_some_action_states"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["game", "state", "turn", "confirmed_at"], name="core_action_game_turn"),
        ),
    ]
