# Generated by Django 4.1.3 on 2022-11-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_add_main_action_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="failure_reason",
            field=models.CharField(
                choices=[
                    ("dead", "Dead"),
                    ("grow_self", "Already it's tile"),
                    ("grow_protected", "Tile is protected"),
                    ("grow_no_neighbor", "Not on a neighbor"),
                ],
                help_text="Reason of the failure.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="action",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("state", "failure"), _negated=True), ("failure_reason__isnull", False), _connector="OR"
                ),
                name="core_action_failure_reason_not_null_if_failed",
            ),
        ),
    ]
