# Generated by Django 4.1.3 on 2022-11-25 01:37
from typing import Any

from django.apps.registry import Apps
from django.db import migrations


def set_level3_for_free_games(apps: Apps, schema_editor: Any) -> None:
    PlayerInGame = apps.get_model("core", "PlayerInGame")
    PlayerInGame.objects.filter(game__mode__in=("free-full", "free-neighbor")).update(level=3)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_add_action_failure_reason"),
    ]

    operations = [
        migrations.RunPython(set_level3_for_free_games, migrations.RunPython.noop),
    ]
