# Generated by Django 4.1.3 on 2022-11-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_set_level3_for_free_games"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                condition=models.Q(("state", "created"), _negated=True),
                fields=["player_in_game", "turn", "state"],
                name="core_action_player_turn",
            ),
        ),
    ]
