# Generated by Django 4.1.3 on 2022-11-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_index_to_count_player_actions"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="playeringame",
            name="core_playeringame_game_player_is_alive",
        ),
        migrations.AddConstraint(
            model_name="playeringame",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_turn__isnull", True)),
                fields=("game", "player"),
                name="core_playeringame_game_player_is_alive",
            ),
        ),
    ]
