# Generated by Django 4.1.3 on 2022-12-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_use_ended_turn_to_know_if_player_dead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="failure_reason",
            field=models.CharField(
                choices=[
                    ("dead", "Dead"),
                    ("grow_self", "Already it's tile"),
                    ("grow_protected", "Tile is protected"),
                    ("grow_no_neighbor", "Not on a neighbor"),
                    ("grow_occupied", "Tile is occupied"),
                    ("attack_empty", "Tile is empty"),
                    ("attack_protected", "Tile is protected"),
                    ("defend_empty", "Tile is empty"),
                    ("defend_other", "Not your tile"),
                ],
                help_text="Reason of the failure.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="playeringame",
            name="banked_actions",
            field=models.FloatField(default=0, help_text="Current number of banked actions points of the player."),
        ),
    ]
