# Generated by Django 4.1.3 on 2022-12-05 08:29
from typing import Any

from django.apps.registry import Apps
from django.db import migrations, models
from django.utils import timezone


def set_welcome_chat_message_sent_at(apps: Apps, schema_editor: Any) -> None:
    Player = apps.get_model("core", "Player")
    Player.objects.filter(welcome_chat_message_sent_at__isnull=True).update(
        welcome_chat_message_sent_at=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_occupied_tile_level_is_float"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="welcome_chat_message_sent_at",
            field=models.DateTimeField(default=None, help_text="Date of the welcome message.", null=True),
        ),
        migrations.AddField(
            model_name="playeringame",
            name="first_in_game_for_player",
            field=models.BooleanField(
                default=False, help_text="Whether this is the first appearance of the player in the game."
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="failure_reason",
            field=models.CharField(
                choices=[
                    ("dead", "Dead"),
                    ("bad-first", "Bad first"),
                    ("grow_self", "Already it's tile"),
                    ("grow_protected", "Tile is protected"),
                    ("grow_no_neighbor", "Not on a neighbor"),
                    ("grow_occupied", "Tile is occupied"),
                    ("attack_empty", "Tile is empty"),
                    ("attack_self", "Already it's tile"),
                    ("attack_protected", "Tile is protected"),
                    ("defend_empty", "Tile is empty"),
                    ("defend_other", "Not your tile"),
                ],
                help_text="Reason of the failure.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="playeringame",
            name="start_tile_col",
            field=models.IntegerField(
                help_text="The grid column of the start tile in the offset `odd-q` coordinate system.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="playeringame",
            name="start_tile_row",
            field=models.IntegerField(
                help_text="The grid row of the start tile in the offset `odd-q` coordinate system.", null=True
            ),
        ),
        migrations.RunPython(set_welcome_chat_message_sent_at, migrations.RunPython.noop),
    ]
