# Generated by Django 4.1.3 on 2022-12-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_handle_messages_in_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="current_turn_step",
            field=models.CharField(
                choices=[
                    ("waiting_for_players", "Waiting for players"),
                    ("collecting_actions", "Collecting actions"),
                    ("random_events_before", "Random events before"),
                    ("executing_actions", "Executing actions"),
                    ("random_events_after", "Random events after"),
                ],
                default="waiting_for_players",
                max_length=255,
            ),
        ),
    ]
