# Generated by Django 4.1.3 on 2022-12-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_game_current_turn_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="current_turn_step",
            field=models.CharField(
                choices=[
                    ("waiting_for_players", "Attente de nouveaux joueurs"),
                    ("collecting_actions", "Collecte des actions"),
                    ("random_events_before", "Évènements aléatoires"),
                    ("executing_actions", "Éxécution des actions"),
                    ("random_events_after", "Évènements aléatoires"),
                ],
                default="waiting_for_players",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="action_type",
            field=models.CharField(
                choices=[("attack", "Attaquer"), ("defend", "Défendre"), ("grow", "Conquérir"), ("bank", "Banquer")],
                help_text="Type of the action.",
                max_length=255,
            ),
        ),
    ]
