# Generated by Django 4.1.3 on 2022-12-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_new_game_step_and_action_types_labels"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="current_turn_started_at",
            new_name="current_turn_step_started_at",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="current_turn_end",
            new_name="current_turn_step_end",
        ),
        migrations.AlterField(
            model_name="game",
            name="current_turn_step_end",
            field=models.DateTimeField(help_text="When the current turn step ends."),
        ),
        migrations.AlterField(
            model_name="game",
            name="current_turn_step_started_at",
            field=models.DateTimeField(auto_now_add=True, help_text="When the current turn step started."),
        ),
    ]
