# Generated by Django 4.1.3 on 2022-12-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_game_step_start_end_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="max_players_allowed",
        ),
    ]
