# Generated by Django 4.1.3 on 2022-12-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_remove_game_max_players_allowed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="current_turn_step_end",
            field=models.DateTimeField(help_text="When the current turn step ends.", null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="current_turn_step_started_at",
            field=models.DateTimeField(help_text="When the current turn step started.", null=True),
        ),
    ]
