# Generated by Django 4.1.3 on 2022-12-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_game_step_times_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drop",
            name="game",
        ),
        migrations.AddField(
            model_name="randomevent",
            name="drop_picked_up",
            field=models.BooleanField(default=False, help_text="Whether the drop was picked up."),
        ),
        migrations.AlterField(
            model_name="randomevent",
            name="drop_actions_amount",
            field=models.FloatField(default=0, help_text="Amount of actions points in the drop."),
        ),
        migrations.AlterField(
            model_name="randomevent",
            name="earthquake_damage",
            field=models.PositiveIntegerField(default=0, help_text="Damage of the earthquake."),
        ),
        migrations.AlterField(
            model_name="randomevent",
            name="earthquake_radius",
            field=models.PositiveIntegerField(default=0, help_text="Radius of the earthquake."),
        ),
        migrations.AlterField(
            model_name="randomevent",
            name="event_type",
            field=models.CharField(
                choices=[("lightning", "Lightning"), ("earthquake", "Earthquake"), ("drop_actions", "Drop actions")],
                help_text="Type of the event.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="randomevent",
            name="lightning_damage",
            field=models.PositiveIntegerField(default=0, help_text="Damage of the lightning."),
        ),
        migrations.AlterField(
            model_name="randomevent",
            name="tile_col",
            field=models.IntegerField(
                help_text="The grid column of the event in the offset `odd-q` coordinate system."
            ),
        ),
        migrations.AlterField(
            model_name="randomevent",
            name="tile_row",
            field=models.IntegerField(help_text="The grid row of the event in the offset `odd-q` coordinate system."),
        ),
        migrations.AddIndex(
            model_name="randomevent",
            index=models.Index(
                condition=models.Q(("drop_picked_up", False), ("event_type", "drop_actions")),
                fields=["game", "tile_col", "tile_row"],
                name="drop_not_picked_up",
            ),
        ),
        migrations.DeleteModel(
            name="Drop",
        ),
    ]
