# Generated by Django 4.1.3 on 2022-12-12 23:48
from typing import Any

from django.apps.registry import Apps
from django.db import migrations, models


def rename_random_events(apps: Apps, schema_editor: Any) -> None:
    RandomEvent = apps.get_model("core", "RandomEvent")
    RandomEvent.objects.filter(event_type__startswith="random_events").update(event_type="random_events")
    Game = apps.get_model("core", "Game")
    Game.objects.filter(current_turn_step__startswith="random_events").update(current_turn_step="random_events")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_random_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="current_turn_step",
            field=models.CharField(
                choices=[
                    ("waiting_for_players", "Attente de nouveaux joueurs"),
                    ("collecting_actions", "Collecte des actions"),
                    ("random_events", "Évènements aléatoires"),
                    ("executing_actions", "Éxécution des actions"),
                    ("erosion", "Érosion"),
                ],
                default="waiting_for_players",
                max_length=255,
            ),
        ),
        migrations.RemoveField(
            model_name="randomevent",
            name="turn_moment",
        ),
        migrations.RunPython(rename_random_events, reverse_code=migrations.RunPython.noop),
    ]
