# Generated by Django 4.1.3 on 2022-12-15 05:51
from typing import Any

from django.apps.registry import Apps
from django.db import migrations, models


def update_last_turn_played(apps: Apps, schema_editor: Any) -> None:
    PlayerInGame = apps.get_model("core", "PlayerInGame")
    for player in PlayerInGame.objects.annotate(last_action_turn=models.Max("action__turn")):
        player.last_turn_played = player.last_action_turn
        player.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_remove_tiles_actions_buttons"),
    ]

    operations = [
        migrations.AddField(
            model_name="playeringame",
            name="last_turn_played",
            field=models.PositiveIntegerField(default=0, help_text="Last turn the player played."),
        ),
        migrations.RunPython(
            code=update_last_turn_played,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
