# Generated by Django 4.1.3 on 2022-12-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_player_last_turn_played"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="failure_reason",
            field=models.CharField(
                choices=[
                    ("dead", "Dead"),
                    ("bad-first", "Bad first"),
                    ("grow_self", "Already it's tile"),
                    ("grow_protected", "Tile is protected"),
                    ("grow_no_neighbor", "Not on a neighbor"),
                    ("attack_protected", "Tile is protected"),
                    ("attack_too_far", "Attack too far"),
                    ("attack_too_many", "Too many attacks"),
                    ("bank_too_many", "Too many banks"),
                ],
                help_text="Reason of the failure.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="end_mode",
            field=models.CharField(
                choices=[
                    ("endless", "Sans fin"),
                    ("turn-limit", "Nombre de tours limité"),
                    ("full-map", "100% occupation"),
                    ("half-map", "50% occupation"),
                ],
                default="endless",
                max_length=255,
            ),
        ),
    ]
