# Generated by Django 4.1.3 on 2022-12-16 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_update_failure_reason_and_end_mode_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="extra_actions",
            field=models.FloatField(default=0, help_text="Extra actions the player can do."),
        ),
        migrations.CreateModel(
            name="ExtraActionOperation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.CharField(help_text="Reason of the operation.", max_length=255)),
                ("value", models.FloatField(default=0, help_text="Value of the operation.")),
                ("done_at", models.DateTimeField(auto_now_add=True, help_text="Date of the operation.")),
                ("reference", models.CharField(help_text="Reference of the operation.", max_length=255)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_action_operations",
                        to="core.player",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
