# Generated by Django 4.1.4 on 2022-12-17 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_player_extra_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extraactionoperation",
            name="player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_action_operations",
                to="core.player",
            ),
        ),
    ]
